In [1]:
import polars as pl

In [2]:
train_df = pl.read_csv('../data/application_train.csv')
test_df = pl.read_csv('../data/application_test.csv')

In [6]:
train_ext = train_df[['SK_ID_CURR', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']]
test_ext = test_df[['SK_ID_CURR', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']]

In [7]:
train_ext

shape: (307_511, 4)
┌────────────┬──────────────┬──────────────┬──────────────┐
│ SK_ID_CURR ┆ EXT_SOURCE_1 ┆ EXT_SOURCE_2 ┆ EXT_SOURCE_3 │
│ ---        ┆ ---          ┆ ---          ┆ ---          │
│ i64        ┆ f64          ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╪══════════════╡
│ 100002     ┆ 0.083037     ┆ 0.262949     ┆ 0.139376     │
│ 100003     ┆ 0.311267     ┆ 0.622246     ┆ null         │
│ 100004     ┆ null         ┆ 0.555912     ┆ 0.729567     │
│ 100006     ┆ null         ┆ 0.650442     ┆ null         │
│ 100007     ┆ null         ┆ 0.322738     ┆ null         │
│ …          ┆ …            ┆ …            ┆ …            │
│ 456251     ┆ 0.14557      ┆ 0.681632     ┆ null         │
│ 456252     ┆ null         ┆ 0.115992     ┆ null         │
│ 456253     ┆ 0.744026     ┆ 0.535722     ┆ 0.218859     │
│ 456254     ┆ null         ┆ 0.514163     ┆ 0.661024     │
│ 456255     ┆ 0.73446      ┆ 0.708569     ┆ 0.113922     │
└────────────┴──────────────┴──────────────┴──────────────┘

In [8]:
final_ext = pl.concat([train_ext, test_ext])
final_ext.write_csv('../data/application_ext.csv')

In [ ]:
final_ext

shape: (356_255, 4)
┌────────────┬──────────────┬──────────────┬──────────────┐
│ SK_ID_CURR ┆ EXT_SOURCE_1 ┆ EXT_SOURCE_2 ┆ EXT_SOURCE_3 │
│ ---        ┆ ---          ┆ ---          ┆ ---          │
│ i64        ┆ f64          ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╪══════════════╡
│ 100002     ┆ 0.083037     ┆ 0.262949     ┆ 0.139376     │
│ 100003     ┆ 0.311267     ┆ 0.622246     ┆ null         │
│ 100004     ┆ null         ┆ 0.555912     ┆ 0.729567     │
│ 100006     ┆ null         ┆ 0.650442     ┆ null         │
│ 100007     ┆ null         ┆ 0.322738     ┆ null         │
│ …          ┆ …            ┆ …            ┆ …            │
│ 456221     ┆ null         ┆ 0.648575     ┆ 0.643026     │
│ 456222     ┆ null         ┆ 0.684596     ┆ null         │
│ 456223     ┆ 0.733503     ┆ 0.63277      ┆ 0.283712     │
│ 456224     ┆ 0.37309      ┆ 0.445701     ┆ 0.595456     │
│ 456250     ┆ null         ┆ 0.456541     ┆ 0.272134     │
└────────────┴──────────────┴──────────────┴──────────────┘

:

In [10]:
final_ext.unique('SK_ID_CURR')

shape: (356_255, 4)
┌────────────┬──────────────┬──────────────┬──────────────┐
│ SK_ID_CURR ┆ EXT_SOURCE_1 ┆ EXT_SOURCE_2 ┆ EXT_SOURCE_3 │
│ ---        ┆ ---          ┆ ---          ┆ ---          │
│ i64        ┆ f64          ┆ f64          ┆ f64          │
╞════════════╪══════════════╪══════════════╪══════════════╡
│ 432701     ┆ null         ┆ 0.450633     ┆ 0.190706     │
│ 143020     ┆ null         ┆ 0.255146     ┆ 0.083364     │
│ 100409     ┆ null         ┆ 0.518013     ┆ 0.340906     │
│ 394952     ┆ null         ┆ 0.574578     ┆ 0.454321     │
│ 103172     ┆ null         ┆ 0.532163     ┆ null         │
│ …          ┆ …            ┆ …            ┆ …            │
│ 244200     ┆ null         ┆ 0.159679     ┆ 0.733815     │
│ 385100     ┆ 0.167843     ┆ 0.714654     ┆ 0.803885     │
│ 273431     ┆ null         ┆ 0.192316     ┆ 0.574447     │
│ 380780     ┆ null         ┆ 0.547741     ┆ null         │
│ 127794     ┆ null         ┆ 0.666676     ┆ 0.42237      │
└────────────┴──────────────┴──────────────┴──────────────┘