In [1]:
import polars as pl
from utils.general_purpose import * 
from utils.validation import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, accuracy_score, roc_auc_score, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer

In [2]:
# VARIABLES
TRAIN_DATA_PATH = "../data/csv_files/train/"
TEST_DATA_PATH = "../data/csv_files/test/"
FEATURE_DEF_PATH = "../data/feature_definitions.csv"

# With polars
POLARS_TRAIN_DATA_PATH = "../data/train/"
POLARS_TEST_DATA_PATH = "../data/test/"

In [3]:
# Set polars config
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(-1)
# Set pandas config (the utils is made by pandas so we need this too)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
train_data = pl.read_parquet(POLARS_TRAIN_DATA_PATH+"train_data_simple.parquet")
train_data.head()

shape: (5, 211)
┌─────────┬───────────────┬────────┬──────────┬────────┬─────────────────────────┬────────────────────────────────┬──────────────┬──────────────────────┬─────────────────────┬──────────────────────┬───────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬───────────────────────────┬─────────────────────────────┬───────────────────────────┬───────────────────────────┬──────────────────────────┬────────────────────────────────┬────────────────────────┬──────────────────┬──────────────┬────────────────────────┬───────────────────────┬───────────────────────┬─────────────────┬──────────────────┬──────────────────┬──────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬──────────────────────────┬────────────────────┬──────────────────────────┬─────────────────┬───────────────┬──────────────┬────────────────────────────┬──────────────────────┬─────────────────────────┬─────────────────────────────────┬───────────────────────┬───────────────────────────┬──────────────────────┬──────────────┬───────────────────────────┬──────────┬────────────────────────┬───────────────────┬─────────────────┬────────────────────────────┬──────────────────────────┬───────────────────┬────────────────────┬──────────────────┬────────────────────────┬──────────────────────────┬────────────────────────────┬─────────────────────────────────┬─────────────────────────┬───────────────────┬───────────────────────┬─────────────────────┬─────────────────────────────┬────────────────────────────────┬───────────────────────────┬────────────────────┬───────────────────────┬─────────────────────────────────┬─────────────┬──────────────┬────────────────────────────┬───────────────────────┬─────────────────┬──────────────────────────┬──────────────────────────────┬─────────────────────────────┬───────────────┬────────────────────────────┬──────────────────────────┬─────────────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┬────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────┬─────────────────────────────────┬───────────────────────┬───────────────────────────┬───────────────────────────┬───────────────────┬────────────────────┬─────────────────────┬────────────────────────────┬────────────────────────┬───────────────────────┬──────────────────────────┬─────────────────────────────┬────────────────┬───────────────────────┬─────────────────────────┬────────────────────────────┬──────────────────────────┬─────────────────────────────────┬──────────────────────┬─────────────────────────────┬────────────────────────────────┬──────────────────────────┬────────────────────────────────┬────────────────────────────────┬───────────────────────┬──────────────────────────────┬───────────────────────────────┬────────────────────────────┬─────────────────────────┬────────────────────────────────┬─────────────────────┬────────────────────────────┬───────────────────────────┬──────────────────────────────┬───────────────────────┬──────────────────────┬───────────────────┬───────────────┬─────────────────┬──────────────┬─────────────────────────────┬─────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────────────────────────┬─────────────┬────────────────────────┬────────────────────────────┬───────────────────────────────┬───────────────────────────┬─────────────┬─────────────────────┬──────────────────────┬───────────────────────────┬──────────────────────────────┬──────────────┬───────────────────┬──────────────────────────┬────────────────────┬────────────────┬─────────────────────┬─────────────────────────┬─────────────────────────┬────────────────┬───────────────────────┬──────────────────┬──────────────────┬──────────────┬──────────────┬─────────────┬──────────────┬─────────────┬──────────────────────┬─────────────────┬───────────────┬───────────────────┬────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┬──────────────────┬─────────────────┬─────────────────┬────────────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬────────────────────┬────────────────┬────────────────┬──────────────────────┬───────────────┬─────────────────────┬─────────────────────┬───────────────────┬───────────────────┬───────────────┬────────────────┬─────────────┬──────────────────────┬────────────────────┬───────────────────────┬───────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target ┆ actualdpdtolerance_344P ┆ amtinstpaidbefduel24m_4187115A ┆ annuity_780A ┆ annuitynextmonth_57A ┆ applicationcnt_361L ┆ applications30d_658L ┆ applicationscnt_1086L ┆ applicationscnt_464L ┆ applicationscnt_629L ┆ applicationscnt_867L ┆ avgdbddpdlast24m_3658932P ┆ avgdbddpdlast3m_4187120P ┆ avgdbdtollast24m_4525197P ┆ avgdpdtolclosure24_3658938P ┆ avginstallast24m_3658937A ┆ avglnamtstart24m_4525187A ┆ avgmaxdpdlast9m_3716943P ┆ avgoutstandbalancel6m_4187114A ┆ avgpmtlast12m_4525200A ┆ bankacctype_710L ┆ cardtype_51L ┆ clientscnt12m_3712952L ┆ clientscnt3m_3712950L ┆ clientscnt6m_3712949L ┆ clientscnt_100L ┆ clientscnt_1022L ┆ clientscnt_1071L ┆ clientscnt_1130L ┆ clientscnt_157L ┆ clientscnt_257L ┆ clientscnt_304L ┆ clientscnt_360L ┆ clientscnt_493L ┆ clientscnt_533L ┆ clientscnt_887L ┆ clientscnt_946L ┆ cntincpaycont9m_3716944L ┆ cntpmts24_3658933L ┆ commnoinclast6m_3546845L ┆ credamount_770A ┆ credtype_322L ┆ currdebt_22A ┆ currdebtcredtyperange_828A ┆ datefirstoffer_1144D ┆ datelastunpaid_3546854D ┆ daysoverduetolerancedd_3976961… ┆ deferredmnthsnum_166L ┆ disbursedcredamount_1113A ┆ disbursementtype_67L ┆ downpmt_116A ┆ dtlastpmtallstes_4499206D ┆ eir_270L ┆ firstclxcampaign_1125D ┆ firstdatedue_489D ┆ homephncnt_628L ┆ inittransactionamount_650A ┆ inittransactioncode_186L ┆ interestrate_311L ┆ isbidproduct_1095L ┆ isdebitcard_729L ┆ lastactivateddate_801D ┆ lastapplicationdate_877D ┆ lastapprcommoditycat_1041M ┆ lastapprcommoditytypec_5251766… ┆ lastapprcredamount_781A ┆ lastapprdate_640D ┆ lastcancelreason_561M ┆ lastdelinqdate_224D ┆ lastrejectcommoditycat_161M ┆ lastrejectcommodtypec_5251769M ┆ lastrejectcredamount_222A ┆ lastrejectdate_50D ┆ lastrejectreason_759M ┆ lastrejectreasonclient_4145040… ┆ lastst_736L ┆ maininc_215A ┆ mastercontrelectronic_519L ┆ mastercontrexist_109L ┆ maxannuity_159A ┆ maxdbddpdlast1m_3658939P ┆ maxdbddpdtollast12m_3658940P ┆ maxdbddpdtollast6m_4187119P ┆ maxdebt4_972A ┆ maxdpdfrom6mto36m_3546853P ┆ maxdpdinstldate_3546855D ┆ maxdpdinstlnum_3546846P ┆ maxdpdlast12m_727P ┆ maxdpdlast24m_143P ┆ maxdpdlast3m_392P ┆ maxdpdlast6m_474P ┆ maxdpdlast9m_1059P ┆ maxdpdtolerance_374P ┆ maxinstallast24m_3658928A ┆ maxlnamtstart6m_4525199A ┆ maxoutstandbalancel12m_4187113… ┆ maxpmtlast3m_4525190A ┆ mindbddpdlast24m_3658935P ┆ mindbdtollast24m_4525191P ┆ mobilephncnt_593L ┆ monthsannuity_845L ┆ numactivecreds_622L ┆ numactivecredschannel_414L ┆ numactiverelcontr_750L ┆ numcontrs3months_479L ┆ numincomingpmts_3546848L ┆ numinstlallpaidearly3d_817L ┆ numinstls_657L ┆ numinstlsallpaid_934L ┆ numinstlswithdpd10_728L ┆ numinstlswithdpd5_4187116L ┆ numinstlswithoutdpd_562L ┆ numinstmatpaidtearly2d_4499204… ┆ numinstpaid_4499208L ┆ numinstpaidearly3d_3546850L ┆ numinstpaidearly3dest_4493216L ┆ numinstpaidearly5d_1087L ┆ numinstpaidearly5dest_4493211L ┆ numinstpaidearly5dobd_4499205L ┆ numinstpaidearly_338L ┆ numinstpaidearlyest_4493214L ┆ numinstpaidlastcontr_4325080L ┆ numinstpaidlate1d_3546852L ┆ numinstregularpaid_973L ┆ numinstregularpaidest_4493210L ┆ numinsttopaygr_769L ┆ numinsttopaygrest_4493213L ┆ numinstunpaidmax_3546851L ┆ numinstunpaidmaxest_4493212L ┆ numnotactivated_1143L ┆ numpmtchanneldd_318L ┆ numrejects9m_859L ┆ opencred_647L ┆ paytype1st_925L ┆ paytype_783L ┆ pctinstlsallpaidearl3d_427L ┆ pctinstlsallpaidlat10d_839L ┆ pctinstlsallpaidlate1d_3546856… ┆ pctinstlsallpaidlate4d_3546849… ┆ pctinstlsallpaidlate6d_3546844… ┆ pmtnum_254L ┆ posfpd10lastmonth_333P ┆ posfpd30lastmonth_3976960P ┆ posfstqpd30lastmonth_3976962P ┆ previouscontdistrict_112M ┆ price_1097A ┆ sellerplacecnt_915L ┆ sellerplacescnt_216L ┆ sumoutstandtotal_3546847A ┆ sumoutstandtotalest_4493215A ┆ totaldebt_9A ┆ totalsettled_863A ┆ totinstallast1m_4525188A ┆ twobodfilling_608L ┆ typesuite_864L ┆ assignmentdate_238D ┆ assignmentdate_4527235D ┆ assignmentdate_4955616D ┆ birthdate_574D ┆ contractssum_5085716L ┆ dateofbirth_337D ┆ dateofbirth_342D ┆ days120_123L ┆ days180_256L ┆ days30_165L ┆ days360_512L ┆ days90_310L ┆ description_5085714M ┆ education_1103M ┆ education_88M ┆ firstquarter_103L ┆ for3years_128L ┆ for3years_504L ┆ for3years_584L ┆ formonth_118L ┆ formonth_206L ┆ formonth_535L ┆ forquarter_1017L ┆ forquarter_462L ┆ forquarter_634L ┆ fortoday_1092L ┆ forweek_1077L ┆ forweek_528L ┆ forweek_601L ┆ foryear_618L ┆ foryear_818L ┆ foryear_850L ┆ fourthquarter_440L ┆ maritalst_385M ┆ maritalst_893M ┆ numberofqueries_373L ┆ pmtaverage_3A ┆ pmtaverage_4527227A ┆ pmtaverage_4955615A ┆ pmtcount_4527229L ┆ pmtcount_4955617L ┆ pmtcount_693L ┆ pmtscount_423L ┆ pmtssum_45A ┆ requesttype_4525192L ┆ responsedate_1012D ┆ responsedate_4527233D ┆ responsedate_4917613D ┆ riskassesment_302T ┆ riskassesment_940T ┆ secondquarter_766L ┆ thirdquarter_1082L │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    ┆ ---                     ┆ ---                            ┆ ---          ┆ ---                  ┆ ---                 ┆ ---                  ┆ ---                   ┆ ---                  ┆ ---                  ┆ ---                  ┆ ---                       ┆ ---                      ┆ ---                       ┆ ---                         ┆ ---                       ┆ ---                       ┆ ---                      ┆ ---                            ┆ ---                    ┆ ---              ┆ ---          ┆ ---                    ┆ ---                   ┆ ---                   ┆ ---             ┆ ---              ┆ ---              ┆ ---              ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---             ┆ ---                      ┆ ---                ┆ ---                      ┆ ---             ┆ ---           ┆ ---          ┆ ---                        ┆ ---                  ┆ ---                     ┆ ---                             ┆ ---                   ┆ ---                       ┆ ---                  ┆ ---          ┆ ---                       ┆ ---      ┆ ---                    ┆ ---               ┆ ---             ┆ ---                        ┆ ---                      ┆ ---               ┆ ---                ┆ ---              ┆ ---                    ┆ ---                      ┆ ---                        ┆ ---                             ┆ ---                     ┆ ---               ┆ ---                   ┆ ---                 ┆ ---                         ┆ ---                            ┆ ---                       ┆ ---                ┆ ---                   ┆ ---                             ┆ ---         ┆ ---          ┆ ---                        ┆ ---                   ┆ ---             ┆ ---                      ┆ ---                          ┆ ---                         ┆ ---           ┆ ---                        ┆ ---                      ┆ ---                     ┆ ---                ┆ ---                ┆ ---               ┆ ---               ┆ ---                ┆ ---                  ┆ ---                       ┆ ---                      ┆ ---                             ┆ ---                   ┆ ---                       ┆ ---                       ┆ ---               ┆ ---                ┆ ---                 ┆ ---                        ┆ ---                    ┆ ---                   ┆ ---                      ┆ ---                         ┆ ---            ┆ ---                   ┆ ---                     ┆ ---                        ┆ ---                      ┆ ---                             ┆ ---                  ┆ ---                         ┆ ---                            ┆ ---                      ┆ ---                            ┆ ---                            ┆ ---                   ┆ ---                          ┆ ---                           ┆ ---                        ┆ ---                     ┆ ---                            ┆ ---                 ┆ ---                        ┆ ---                       ┆ ---                          ┆ ---                   ┆ ---                  ┆ ---               ┆ ---           ┆ ---             ┆ ---          ┆ ---                         ┆ ---                         ┆ ---                             ┆ ---                             ┆ ---                             ┆ ---         ┆ ---                    ┆ ---                        ┆ ---                           ┆ ---                       ┆ ---         ┆ ---                 ┆ ---                  ┆ ---                       ┆ ---                          ┆ ---          ┆ ---               ┆ ---                      ┆ ---                ┆ ---            ┆ ---                 ┆ ---                     ┆ ---                     ┆ ---            ┆ ---                   ┆ ---              ┆ ---              ┆ ---          ┆ ---          ┆ ---         ┆ ---          ┆ ---         ┆ ---                  ┆ ---             ┆ ---           ┆ ---               ┆ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           ┆ ---              ┆ ---             ┆ ---             ┆ ---            ┆ ---           ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---                ┆ ---            ┆ ---            ┆ ---                  ┆ ---           ┆ ---                 ┆ ---                 ┆ ---               ┆ ---               ┆ ---           ┆ ---            ┆ ---         ┆ ---                  ┆ ---                ┆ ---                   ┆ ---                   ┆ ---                ┆ ---                ┆ ---                ┆ ---                │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    ┆ f64                     ┆ f64                            ┆ f64          ┆ f64                  ┆ f64                 ┆ f64                  ┆ f64                   ┆ f64                  ┆ f64                  ┆ f64                  ┆ f64                       ┆ f64                      ┆ f64                       ┆ f64                         ┆ f64                       ┆ f64                       ┆ f64                      ┆ f64                            ┆ f64                    ┆ str              ┆ str          ┆ f64                    ┆ f64                   ┆ f64                   ┆ f64             ┆ f64              ┆ f64              ┆ f64              ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64             ┆ f64                      ┆ f64                ┆ f64                      ┆ f64             ┆ str           ┆ f64          ┆ f64                        ┆ str                  ┆ str                     ┆ f64                             ┆ f64                   ┆ f64                       ┆ str                  ┆ f64          ┆ str                       ┆ f64      ┆ str                    ┆ str               ┆ f64             ┆ f64                        ┆ str                      ┆ f64               ┆ bool               ┆ bool             ┆ str                    ┆ str                      ┆ str                        ┆ str                             ┆ f64                     ┆ str               ┆ str                   ┆ str                 ┆ str                         ┆ str                            ┆ f64                       ┆ str                ┆ str                   ┆ str                             ┆ str         ┆ f64          ┆ f64                        ┆ f64                   ┆ f64             ┆ f64                      ┆ f64                          ┆ f64                         ┆ f64           ┆ f64                        ┆ str                      ┆ f64                     ┆ f64                ┆ f64                ┆ f64               ┆ f64               ┆ f64                ┆ f64                  ┆ f64                       ┆ f64                      ┆ f64                             ┆ f64                   ┆ f64                       ┆ f64                       ┆ f64               ┆ f64                ┆ f64                 ┆ f64                        ┆ f64                    ┆ f64                   ┆ f64                      ┆ f64                         ┆ f64            ┆ f64                   ┆ f64                     ┆ f64                        ┆ f64                      ┆ f64                             ┆ f64                  ┆ f64                         ┆ f64                            ┆ f64                      ┆ f64                            ┆ f64                            ┆ f64                   ┆ f64                          ┆ f64                           ┆ f64                        ┆ f64                     ┆ f64                            ┆ f64                 ┆ f64                        ┆ f64                       ┆ f64                          ┆ f64                   ┆ f64                  ┆ f64               ┆ bool          ┆ str             ┆ str          ┆ f64                         ┆ f64                         ┆ f64                             ┆ f64                             ┆ f64                             ┆ f64         ┆ f64                    ┆ f64                        ┆ f64                           ┆ str                       ┆ f64         ┆ f64                 ┆ f64                  ┆ f64                       ┆ f64                          ┆ f64          ┆ f64               ┆ f64                      ┆ str                ┆ str            ┆ str                 ┆ str                     ┆ str                     ┆ str            ┆ f64                   ┆ str              ┆ str              ┆ f64          ┆ f64          ┆ f64         ┆ f64          ┆ f64         ┆ str                  ┆ str             ┆ str           ┆ f64               ┆ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           ┆ f64              ┆ f64             ┆ f64             ┆ f64            ┆ f64           ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ f64                ┆ str            ┆ str            ┆ f64                  ┆ f64           ┆ f64                 ┆ f64                 ┆ f64               ┆ f64               ┆ f64           ┆ f64            ┆ f64         ┆ str                  ┆ str                ┆ str                   ┆ str                   ┆ str                ┆ f64                ┆ f64                ┆ f64                │

In [6]:
train_data_feature = get_feature_definitions(data_file_path=POLARS_TRAIN_DATA_PATH+"train_data_simple.parquet",
                                             feature_definitions_csv=FEATURE_DEF_PATH)
train_data_feature

,Variable,Description,Data Type
1,actualdpdtolerance_344P,DPD of client with tolerance.,double
14,amtinstpaidbefduel24m_4187115A,Number of instalments paid before due date in the last 24 months.,double
17,annuity_780A,Monthly annuity amount.,double
19,annuitynextmonth_57A,Next month's amount of annuity.,double
20,applicationcnt_361L,Number of applications associated with the same email address as the client.,double
21,applications30d_658L,Number of applications made by the client in the last 30 days.,double
22,applicationscnt_1086L,Number of applications associated with the same phone number.,double
23,applicationscnt_464L,Number of applications made in the last 30 days by other clients with the same employer as the applicant.,double
24,applicationscnt_629L,Number of applications with the same employer in the last 7 days.,double
25,applicationscnt_867L,Number of applications associated with the same mobile phone.,double
27,assignmentdate_238D,Tax authority data - date of assignment.,large_string
28,assignmentdate_4527235D,Tax authority data - Date of assignment.,large_string
29,assignmentdate_4955616D,Tax authority assignment date.,large_string
30,avgdbddpdlast24m_3658932P,Average days past or before due of payment during the last 24 months.,double
31,avgdbddpdlast3m_4187120P,Average days past or before due of payment during the last 3 months.,double
32,avgdbdtollast24m_4525197P,Average days of payment before due date within the last 24 months (with tolerance).,double
33,avgdpdtolclosure24_3658938P,"Average DPD (days past due) with tolerance within the past 24 months from the maximum closure date, assuming that the contract is finished. If the contract is ongoing, the calculation is based on the current date.",double
34,avginstallast24m_3658937A,Average instalments paid by the client over the past 24 months.,double
35,avglnamtstart24m_4525187A,Average loan amount in the last 24 months.,double
36,avgmaxdpdlast9m_3716943P,Average Days Past Due (DPD) of the client in last 9 months.,double
37,avgoutstandbalancel6m_4187114A,Average outstanding balance of applicant for the last 6 months.,double
38,avgpmtlast12m_4525200A,Average of payments made by the client in the last 12 months.,double
39,bankacctype_710L,Type of applicant's bank account.,large_string
41,birthdate_574D,Client's date of birth (credit bureau data).,large_string
46,cardtype_51L,Type of credit card.,large_string
52,clientscnt_100L,Number of applications with matching employer's phone and client's.,double
53,clientscnt_1022L,Number of clients sharing the same mobile phone.,double
54,clientscnt_1071L,Number of applications where the alternative phone number matches that of the client.,double
55,clientscnt_1130L,Number of applications where client's phone number matches the alternative phone contact.,double
57,clientscnt_157L,Number of clients whose employer has the same phone number as the client.,double
58,clientscnt_257L,Number of clients that share an alternative phone number with the applicant.,double
59,clientscnt_304L,Number of clients with the same phone number.,double
60,clientscnt_360L,Number of clients that have the same alternative phone number and employer's phone number.,double
61,clientscnt_493L,Number of clients with matching phone numbers for both the employer and the client.,double
62,clientscnt_533L,Number of clients with same client's and alternative's phone number,double
63,clientscnt_887L,Number of clients sharing the same employer's phone number.,double
64,clientscnt_946L,Number of clients with matching mobile and employer's number.,double
65,clientscnt12m_3712952L,Number of clients that have used the same mobile phone as the applicant in the past 12 months.,double
66,clientscnt3m_3712950L,Number of clients who have the same mobile phone number in the last 3 months.,double
67,clientscnt6m_3712949L,Total number of clients who have used the same mobile number in the last 6 months.,double
68,cntincpaycont9m_3716944L,Number of incoming payments in the past 9 months.,double
69,cntpmts24_3658933L,Number of months with any incoming payment in last 24 months.,double
76,commnoinclast6m_3546845L,Number of communications indicating low income in the last six months.,double
84,contractssum_5085716L,Total sum of values of contracts retrieved from external credit bureau.,double
101,credamount_770A,Loan amount or credit card limit.,double
110,credtype_322L,Type of credit.,large_string
112,currdebt_22A,Current debt amount of the client.,double
114,currdebtcredtyperange_828A,Current amount of debt of the applicant.,double
116,datefirstoffer_1144D,Date of first customer relationship management (CRM) offer.,large_string
118,datelastunpaid_3546854D,Date of the last unpaid instalment.,large_string
119,dateofbirth_337D,Client's date of birth.,large_string
120,dateofbirth_342D,Client's date of birth.,large_string
126,days120_123L,Number of credit bureau queries for the last 120 days.,double
127,days180_256L,Number of credit bureau queries for last 180 days.,double
128,days30_165L,Number of credit bureau queries for the last 30 days.,double
129,days360_512L,Number of Credit Bureau queries for last 360 days.,double
130,days90_310L,Number of credit bureau queries for the last 90 days.,double
131,daysoverduetolerancedd_3976961L,Number of days that past after the due date (with tolerance).,double
137,deferredmnthsnum_166L,Number of deferred months.,double
139,description_5085714M,Categorization of clients by credit bureau.,large_string
140,disbursedcredamount_1113A,Disbursed credit amount after consolidation.,double
141,disbursementtype_67L,Type of disbursement.,large_string
143,downpmt_116A,Amount of downpayment.,double
158,dtlastpmtallstes_4499206D,Date of last payment made by the applicant.,large_string
159,education_1103M,Level of education of the client provided by external source.,large_string
161,education_88M,Education level of the client.,large_string
163,eir_270L,Interest rate.,double
180,firstclxcampaign_1125D,Date of the client's first campaign.,large_string
181,firstdatedue_489D,Date of the first due date.,large_string
183,firstquarter_103L,Number of results obtained from credit bureau in the first quarter.,double
184,for3years_128L,Number of rejected applications in the past 3 years.,double
185,for3years_504L,Client's credit history data over the last three years.,double
186,for3years_584L,Number of cancellations in the last 3 years.,double
187,formonth_118L,Number of rejections in a month.,double
188,formonth_206L,Number of cancelations in the previous month.,double
189,formonth_535L,Credit history for the last month.,double
190,forquarter_1017L,Number of cancellations recorded in the credit bureau in the last quarter.,double
191,forquarter_462L,Number of credit applications that were rejected in the last quarter.,double
192,forquarter_634L,Credit history for the last quarter.,double
193,fortoday_1092L,Client's credit history for today.,double
194,forweek_1077L,Number of cancelations in the last week.,double
195,forweek_528L,Credit history for the last week.,double
196,forweek_601L,Number of rejected applications in the last week.,double
197,foryear_618L,Number of application rejections in the previous year.,double
198,foryear_818L,Number of cancelations that occurred in last year.,double
199,foryear_850L,Credit history for the last year.,double
200,fourthquarter_440L,Number of results in fourth quarter.,double
202,homephncnt_628L,Number of distinct home phones on client's application.,double
206,inittransactionamount_650A,Initial transaction amount of the credit application.,double
207,inittransactioncode_186L,Transaction type of the initial credit transaction.,large_string
215,interestrate_311L,The interest rate of the active credit contract.,double
219,isbidproduct_1095L,Flag indicating if the product is a cross-sell.,bool
223,isdebitcard_729L,Flag indicating if the product is a debit card.,bool
229,lastactivateddate_801D,Contract activation date for previous applications.,large_string
230,lastapplicationdate_877D,Date of previous customer's application.,large_string
231,lastapprcommoditycat_1041M,Commodity category of the last loan applications made by the applicant.,large_string
232,lastapprcommoditytypec_5251766M,Commodity type of the last application.,large_string
233,lastapprcredamount_781A,Credit amount from the client's last application.,double
234,lastapprdate_640D,Date of approval on client's most recent previous application.,large_string
235,lastcancelreason_561M,Cancellation reason of the last application.,large_string
236,lastdelinqdate_224D,Date of the last delinquency occurrence.,large_string
240,lastrejectcommoditycat_161M,Category of commodity in the applicant's last rejected application.,large_string
241,lastrejectcommodtypec_5251769M,Commodity type of the last rejected application.,large_string
242,lastrejectcredamount_222A,Credit amount on last rejected application.,double
243,lastrejectdate_50D,Date of most recent rejected application by the applicant.,large_string
244,lastrejectreason_759M,Reason for rejection on the most recent rejected application.,large_string
245,lastrejectreasonclient_4145040M,Reason for the client's last loan rejection.,large_string
247,lastst_736L,Status of the client's previous credit application.,large_string
251,maininc_215A,Client's primary income amount.,double
254,maritalst_385M,Marital status of the client.,large_string
256,maritalst_893M,Marital status of the client,large_string
257,mastercontrelectronic_519L,Flag indicating the existence of the master contract for the client.,double
258,mastercontrexist_109L,Flag indicating whether or not the applicant has an existing master contract.,double
259,maxannuity_159A,Maximum annuity previously obtained by client.,double
261,maxdbddpdlast1m_3658939P,Maximum number of days past due in the last month. A negative value indicates the number of days before the due date.,double
262,maxdbddpdtollast12m_3658940P,Maximum number of days past due in last 12 months. A negative value implies days before due date.,double
263,maxdbddpdtollast6m_4187119P,Maximum number of days past due in last 6 months. This predictor takes the value as a negative number when it represents days before due date.,double
264,maxdebt4_972A,Maximal principal debt of the client in the history older than 4 months.,double
266,maxdpdfrom6mto36m_3546853P,Maximum Days Past Due (DPD) in the period ranging from 6 to 36 months.,double
267,maxdpdinstldate_3546855D,Date of instalment on which client was most days past due.,large_string
268,maxdpdinstlnum_3546846P,Instalment number of which client was most days past due.,double
269,maxdpdlast12m_727P,Maximum days past due in the past 12 months.,double
270,maxdpdlast24m_143P,Maximal days past due in the last 24 months.,double
271,maxdpdlast3m_392P,Maximum number of days past due in last 3 months.,double
272,maxdpdlast6m_474P,Maximum days past due in the last 6 months.,double
273,maxdpdlast9m_1059P,Maximum days past due in last 9 months.,double
274,maxdpdtolerance_374P,Maximum number of days past due (with tolerance).,double
276,maxinstallast24m_3658928A,Maximum instalment in the last 24 months,double
277,maxlnamtstart6m_4525199A,Maximum loan amount started in the last 6 months.,double
278,maxoutstandbalancel12m_4187113A,Maximum outstanding balance in the last 12 months.,double
279,maxpmtlast3m_4525190A,Maximum payment made by the client in the last 3 months.,double
280,mindbddpdlast24m_3658935P,Minimum days past due (or days before due) in last 24 months.,double
281,mindbdtollast24m_4525191P,Minimum days before due in last 24 months.,double
282,mobilephncnt_593L,Number of persons with the same mobile phone number.,double
285,monthsannuity_845L,Monthly annuity amount for the applicant.,double
290,numactivecreds_622L,Number of active credits.,double
291,numactivecredschannel_414L,Number of active credits.,double
292,numactiverelcontr_750L,Number of active revolving credits.,double
306,numberofqueries_373L,Number of queries to credit bureau.,double
307,numcontrs3months_479L,Number of contracts in last 3 months.,double
308,numincomingpmts_3546848L,Number of incoming payments.,double
309,numinstlallpaidearly3d_817L,Number of instalments paid at least 3 days prior to their due date.,double
310,numinstls_657L,Number of instalments.,double
311,numinstlsallpaid_934L,Number of paid instalments.,double
312,numinstlswithdpd10_728L,Number of instalments that were overdue for 10 or more days.,double
313,numinstlswithdpd5_4187116L,Number of instalments that were overdue by at least 5 days.,double
314,numinstlswithoutdpd_562L,Number of instalments that were not past due date.,double
315,numinstmatpaidtearly2d_4499204L,Number of instalments that have been paid more than 2 days before their due date.,double
316,numinstpaid_4499208L,Number of paid instalments.,double
317,numinstpaidearly_338L,Number of installments paid prior to the due date.,double
318,numinstpaidearly3d_3546850L,Number of instalments paid more than three days before the due date.,double
319,numinstpaidearly3dest_4493216L,Number of instalments that have been paid more than 3 days in advance of the due date.,double
320,numinstpaidearly5d_1087L,Number of instalments paid more than 5 days prior to the due date.,double
321,numinstpaidearly5dest_4493211L,Number of instalments that were paid more than 5 days before the due date.,double
322,numinstpaidearly5dobd_4499205L,Number of installments paid more than 5 days prior to the due date.,double
323,numinstpaidearlyest_4493214L,Number of instalments paid before the due date.,double
324,numinstpaidlastcontr_4325080L,Number of paid installments from the client's last contract.,double
325,numinstpaidlate1d_3546852L,Number of instalments paid more than 1 day past their due date.,double
326,numinstregularpaid_973L,Number of fully paid regular installments in the client's previous contracts.,double
327,numinstregularpaidest_4493210L,Number of fully paid regular installments on clients' previous contracts.,double
328,numinsttopaygr_769L,Number of unpaid instalments.,double
329,numinsttopaygrest_4493213L,Number of unpaid instalments.,double
330,numinstunpaidmax_3546851L,Maximum number of unpaid instalments.,double
331,numinstunpaidmaxest_4493212L,Maximum number of unpaid instalments.,double
332,numnotactivated_1143L,Number of non-activated credits.,double
333,numpmtchanneldd_318L,Number of previous loan contracts for the applicant that had direct debit as payment channel.,double
334,numrejects9m_859L,Number of credit applications that were rejected in the last 9 months.,double
335,opencred_647L,Number of active loans from the previous application.,bool
356,paytype_783L,Type of payment.,large_string
357,paytype1st_925L,Type of first payment of the client.,large_string
359,pctinstlsallpaidearl3d_427L,Percentage of installments paid at least 3 days prior to the due date.,double
360,pctinstlsallpaidlat10d_839L,Percentage of installments that were paid 10 or more days after the due date.,double
361,pctinstlsallpaidlate1d_3546856L,Percentage of installments that are paid 1 or more days after the due date.,double
362,pctinstlsallpaidlate4d_3546849L,Percentage of installments that were paid 4 or more days past their due date.,double
363,pctinstlsallpaidlate6d_3546844L,Percentage of installments that were paid 6 or more days past their due date.,double
372,pmtaverage_3A,Average of tax deductions.,double
373,pmtaverage_4527227A,Average of tax deductions.,double
374,pmtaverage_4955615A,Average of tax deductions.,double
375,pmtcount_4527229L,Number of tax deductions.,double
376,pmtcount_4955617L,Number of tax deductions.,double
377,pmtcount_693L,Number of tax deductions.,double
380,pmtnum_254L,Total number of loan payments made by the client.,double
394,pmtscount_423L,Number of tax deduction payments.,double
395,pmtssum_45A,Sum of tax deductions for the client.,double
396,posfpd10lastmonth_333P,Average FPD10 (Share of contracts with first installment past due more than 10 days) from point of sales that processed contract in the previous month.,double
397,posfpd30lastmonth_3976960P,Average FPD30 (Share of contracts with first installment past due more than 30 days) from point of sales that processed contract in the previous month.,double
398,posfstqpd30lastmonth_3976962P,"Average FSTPD30 (share of contracts with first, second, or third installment past due more than 30 days) from point of sale that processed contract in the last month.",double
400,previouscontdistrict_112M,Contact district of the client's previous approved application.,large_string
401,price_1097A,Credit price.,double
419,requesttype_4525192L,Tax authority request type.,large_string
425,responsedate_1012D,Tax authority's response date.,large_string
426,responsedate_4527233D,Tax authority's response date.,large_string
427,responsedate_4917613D,Tax authority's response date.,large_string
429,riskassesment_302T,Estimated probability that the client will default on their credit obligation within the next year.,large_string
430,riskassesment_940T,Estimate of client's creditworthiness.,double
435,secondquarter_766L,Number of results in second quarter.,double
436,sellerplacecnt_915L,Number of sellerplaces where the same client's document was used.,double
437,sellerplacescnt_216L,Number of sellerplaces where the same client's mobile phone was used.,double
446,sumoutstandtotal_3546847A,Sum of total outstanding amount.,double
447,sumoutstandtotalest_4493215A,Sum of total outstanding amount.,double
449,thirdquarter_1082L,Number of results in third quarter.,double
454,totaldebt_9A,Total amount of debt.,double
459,totalsettled_863A,Sum of all payments made by the client.,double
460,totinstallast1m_4525188A,Total amount of monthly instalments paid in the previous month.,double
461,twobodfilling_608L,Type of application process.,large_string
463,typesuite_864L,Persons accompanying the client during the loan application process.,large_string