# Initial Setup

In [40]:
import polars as pl 
import pandas as pd
from utils import get_feature_definitions

In [41]:
# VARIABLES
TRAIN_DATA_PATH = "../data/train/"
TEST_DATA_PATH = "../data/test/"
FEATURE_DEF_PATH = "../data/feature_definitions.csv"

In [42]:
# Set polars config
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)

# Set pandas config (the utils is made by pandas so we need this too)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Business Understanding

Consumer finance providers must accurately determine which clients can repay a loan and which cannot and data is key. If data science could help better predict one’s repayment capabilities, loans might become more accessible to those who may benefit from them the most.

# Data Understanding

## Train base dataset

In [43]:
# Get the columns 
train_base_feature = get_feature_definitions(parquet_file=TRAIN_DATA_PATH+"train_base.parquet",
                                             feature_definitions_csv=FEATURE_DEF_PATH)
train_base_feature

Empty DataFrame
Columns: [Variable, Description]
Index: []

In [44]:
# Read train base 
train_base = pl.read_parquet(TRAIN_DATA_PATH+"train_base.parquet")

In [45]:
train_base.head()

shape: (5, 5)
┌─────────┬───────────────┬────────┬──────────┬────────┐
│ case_id ┆ date_decision ┆ MONTH  ┆ WEEK_NUM ┆ target │
│ ---     ┆ ---           ┆ ---    ┆ ---      ┆ ---    │
│ i64     ┆ str           ┆ i64    ┆ i64      ┆ i64    │
╞═════════╪═══════════════╪════════╪══════════╪════════╡
│ 0       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 1       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 2       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 0      │
│ 3       ┆ 2019-01-03    ┆ 201901 ┆ 0        ┆ 0      │
│ 4       ┆ 2019-01-04    ┆ 201901 ┆ 0        ┆ 1      │
└─────────┴───────────────┴────────┴──────────┴────────┘

In [46]:
train_base.describe()

shape: (9, 6)
┌────────────┬───────────────┬───────────────┬───────────────┬────────────┬────────────┐
│ statistic  ┆ case_id       ┆ date_decision ┆ MONTH         ┆ WEEK_NUM   ┆ target     │
│ ---        ┆ ---           ┆ ---           ┆ ---           ┆ ---        ┆ ---        │
│ str        ┆ f64           ┆ str           ┆ f64           ┆ f64        ┆ f64        │
╞════════════╪═══════════════╪═══════════════╪═══════════════╪════════════╪════════════╡
│ count      ┆ 1.526659e6    ┆ 1526659       ┆ 1.526659e6    ┆ 1.526659e6 ┆ 1.526659e6 │
│ null_count ┆ 0.0           ┆ 0             ┆ 0.0           ┆ 0.0        ┆ 0.0        │
│ mean       ┆ 1.2861e6      ┆ null          ┆ 201936.287982 ┆ 40.769036  ┆ 0.031437   │
│ std        ┆ 718946.592285 ┆ null          ┆ 44.735975     ┆ 23.797981  ┆ 0.174496   │
│ min        ┆ 0.0           ┆ 2019-01-01    ┆ 201901.0      ┆ 0.0        ┆ 0.0        │
│ 25%        ┆ 766198.0      ┆ null          ┆ 201906.0      ┆ 23.0       ┆ 0.0        │
│ 50%        ┆ 1.357358e6    ┆ null          ┆ 201910.0      ┆ 40.0       ┆ 0.0        │
│ 75%        ┆ 1.739023e6    ┆ null          ┆ 202001.0      ┆ 55.0       ┆ 0.0        │
│ max        ┆ 2.703454e6    ┆ 2020-10-05    ┆ 202010.0      ┆ 91.0       ┆ 1.0        │
└────────────┴───────────────┴───────────────┴───────────────┴────────────┴────────────┘

The train base have no Null columns

## Train static dataset

In [47]:
# Get the feature definitions 
train_static_feature = get_feature_definitions(parquet_file=TRAIN_DATA_PATH+"train_static_0_0.parquet",
                                             feature_definitions_csv=FEATURE_DEF_PATH)
train_static_feature.shape

(167, 2)

This is the DEPTH 0 type, which mean that this is the feature that can directly be used in machine learning model

In [48]:
train_static_0 = pl.read_parquet(TRAIN_DATA_PATH+"train_static_0_0.parquet")
train_static_1 = pl.read_parquet(TRAIN_DATA_PATH+"train_static_0_1.parquet")

In [49]:
train_static_0.columns

['case_id',
 'actualdpdtolerance_344P',
 'amtinstpaidbefduel24m_4187115A',
 'annuity_780A',
 'annuitynextmonth_57A',
 'applicationcnt_361L',
 'applications30d_658L',
 'applicationscnt_1086L',
 'applicationscnt_464L',
 'applicationscnt_629L',
 'applicationscnt_867L',
 'avgdbddpdlast24m_3658932P',
 'avgdbddpdlast3m_4187120P',
 'avgdbdtollast24m_4525197P',
 'avgdpdtolclosure24_3658938P',
 'avginstallast24m_3658937A',
 'avglnamtstart24m_4525187A',
 'avgmaxdpdlast9m_3716943P',
 'avgoutstandbalancel6m_4187114A',
 'avgpmtlast12m_4525200A',
 'bankacctype_710L',
 'cardtype_51L',
 'clientscnt12m_3712952L',
 'clientscnt3m_3712950L',
 'clientscnt6m_3712949L',
 'clientscnt_100L',
 'clientscnt_1022L',
 'clientscnt_1071L',
 'clientscnt_1130L',
 'clientscnt_136L',
 'clientscnt_157L',
 'clientscnt_257L',
 'clientscnt_304L',
 'clientscnt_360L',
 'clientscnt_493L',
 'clientscnt_533L',
 'clientscnt_887L',
 'clientscnt_946L',
 'cntincpaycont9m_3716944L',
 'cntpmts24_3658933L',
 'commnoinclast6m_3546845L',
 'credamount_770A',
 'credtype_322L',
 'currdebt_22A',
 'currdebtcredtyperange_828A',
 'datefirstoffer_1144D',
 'datelastinstal40dpd_247D',
 'datelastunpaid_3546854D',
 'daysoverduetolerancedd_3976961L',
 'deferredmnthsnum_166L',
 'disbursedcredamount_1113A',
 'disbursementtype_67L',
 'downpmt_116A',
 'dtlastpmtallstes_4499206D',
 'eir_270L',
 'equalitydataagreement_891L',
 'equalityempfrom_62L',
 'firstclxcampaign_1125D',
 'firstdatedue_489D',
 'homephncnt_628L',
 'inittransactionamount_650A',
 'inittransactioncode_186L',
 'interestrate_311L',
 'interestrategrace_34L',
 'isbidproduct_1095L',
 'isbidproductrequest_292L',
 'isdebitcard_729L',
 'lastactivateddate_801D',
 'lastapplicationdate_877D',
 'lastapprcommoditycat_1041M',
 'lastapprcommoditytypec_5251766M',
 'lastapprcredamount_781A',
 'lastapprdate_640D',
 'lastcancelreason_561M',
 'lastdelinqdate_224D',
 'lastdependentsnum_448L',
 'lastotherinc_902A',
 'lastotherlnsexpense_631A',
 'lastrejectcommoditycat_161M',
 'lastrejectcommodtypec_5251769M',
 'lastrejectcredamount_222A',
 'lastrejectdate_50D',
 'lastrejectreason_759M',
 'lastrejectreasonclient_4145040M',
 'lastrepayingdate_696D',
 'lastst_736L',
 'maininc_215A',
 'mastercontrelectronic_519L',
 'mastercontrexist_109L',
 'maxannuity_159A',
 'maxannuity_4075009A',
 'maxdbddpdlast1m_3658939P',
 'maxdbddpdtollast12m_3658940P',
 'maxdbddpdtollast6m_4187119P',
 'maxdebt4_972A',
 'maxdpdfrom6mto36m_3546853P',
 'maxdpdinstldate_3546855D',
 'maxdpdinstlnum_3546846P',
 'maxdpdlast12m_727P',
 'maxdpdlast24m_143P',
 'maxdpdlast3m_392P',
 'maxdpdlast6m_474P',
 'maxdpdlast9m_1059P',
 'maxdpdtolerance_374P',
 'maxinstallast24m_3658928A',
 'maxlnamtstart6m_4525199A',
 'maxoutstandbalancel12m_4187113A',
 'maxpmtlast3m_4525190A',
 'mindbddpdlast24m_3658935P',
 'mindbdtollast24m_4525191P',
 'mobilephncnt_593L',
 'monthsannuity_845L',
 'numactivecreds_622L',
 'numactivecredschannel_414L',
 'numactiverelcontr_750L',
 'numcontrs3months_479L',
 'numincomingpmts_3546848L',
 'numinstlallpaidearly3d_817L',
 'numinstls_657L',
 'numinstlsallpaid_934L',
 'numinstlswithdpd10_728L',
 'numinstlswithdpd5_4187116L',
 'numinstlswithoutdpd_562L',
 'numinstmatpaidtearly2d_4499204L',
 'numinstpaid_4499208L',
 'numinstpaidearly3d_3546850L',
 'numinstpaidearly3dest_4493216L',
 'numinstpaidearly5d_1087L',
 'numinstpaidearly5dest_4493211L',
 'numinstpaidearly5dobd_4499205L',
 'numinstpaidearly_338L',
 'numinstpaidearlyest_4493214L',
 'numinstpaidlastcontr_4325080L',
 'numinstpaidlate1d_3546852L',
 'numinstregularpaid_973L',
 'numinstregularpaidest_4493210L',
 'numinsttopaygr_769L',
 'numinsttopaygrest_4493213L',
 'numinstunpaidmax_3546851L',
 'numinstunpaidmaxest_4493212L',
 'numnotactivated_1143L',
 'numpmtchanneldd_318L',
 'numrejects9m_859L',
 'opencred_647L',
 'paytype1st_925L',
 'paytype_783L',
 'payvacationpostpone_4187118D',
 'pctinstlsallpaidearl3d_427L',
 'pctinstlsallpaidlat10d_839L',
 'pctinstlsallpaidlate1d_3546856L',
 'pctinstlsallpaidlate4d_3546849L',
 'pctinstlsallpaidlate6d_3546844L',
 'pmtnum_254L',
 'posfpd10lastmonth_333P',
 'posfpd30lastmonth_3976960P',
 'posfstqpd30lastmonth_3976962P',
 'previouscontdistrict_112M',
 'price_1097A',
 'sellerplacecnt_915L',
 'sellerplacescnt_216L',
 'sumoutstandtotal_3546847A',
 'sumoutstandtotalest_4493215A',
 'totaldebt_9A',
 'totalsettled_863A',
 'totinstallast1m_4525188A',
 'twobodfilling_608L',
 'typesuite_864L',
 'validfrom_1069D']